version: "3.9"

services:
  #questDB
  questDB:
    container_name: questDB
    image: questdb/questdb:latest
    profiles:
      - database
      - all
    ports:
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./questdb:/var/lib/questdb
         
  mongoDB:
    image: mongo
    container_name: mongodb
    profiles:
      - database
      - all
    #restart: always
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASDWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    #restart: always
    profiles:
      - database
      - all
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASDWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASDWORD}@mongoDB:27017

    depends_on:
      - mongoDB

  stock-scraper:
    container_name: StockScraper
    build: ./src/Stocks/
    profiles:
      - all
    environment:
      - STOCKSCRAPER_QUESTDB_HOST=questdb
      - STOCKSCRAPER_QUESTDB_ILP_PORT=9009
      - STOCKSCRAPER_QUESTDB_PORT=9000
      - STOCKSCRAPER_MODE=Single #Single or Scheduled
      - STOCKSCRAPER_TICKERS_DIR=/var/lib/stock-scraper

    volumes:
      - ./tickers:/var/lib/stock-scraper

    depends_on:
      - questDB