name: Publish to Docker-Hub

on: workflow_dispatch


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push news scraper
        uses: docker/build-push-action@v3
        with:
          context: ./src/news
          file: ./src/news/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/finance-data-scraper:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/finance-data-scraper:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/finance-data-scraper:buildcache,mode=max
